const productTypes = {
	GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
	GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
	GET_ALL_PRODUCTS_FAIL: "GET_ALL_PRODUCTS_FAIL",
	GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
	GET_PRODUCT_DETAILS_SUCCESS: "GET_PRODUCT_DETAILS_SUCCESS",
	GET_PRODUCT_DETAILS_FAIL: "GET_PRODUCT_DETAILS_FAIL"
};

export default productTypes;
